### GET ALL ORDERS
GET http://localhost:3003/orders/

### GET ALL ORDERS ON SERVER
GET http://103.49.238.82:3003/orders/

### GET ALL ORDERS
GET http://103.49.238.82:8010


### CREATE ORDERS
POST http://localhost:3003/orders/
Content-Type: application/json

{
    "productName": "New Kindle",
    "price": "991000",
    "sellerName": "Edi S"
}

### DELETE ORDERS
DELETE http://localhost:3003/orders/delete/67209b047f20ea4f0f62ea18
Authorization: secret