### GET ALL ORDERS
GET http://localhost:3003/orders/

### GET ALL ORDERS
GET http://localhost:8010


### CREATE ORDERS
POST http://localhost:8010
Content-Type: application/json

{
    "productName": "New Kindle ",
    "price": 991000,
    "sellerName": "Edi S"
}

### DELETE ORDERS
DELETE http://localhost:8010/delete/67209b047f20ea4f0f62ea18
Authorization: secret