version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3003:3003"

  notification-services:
    build: ./notifications
    depends_on:
      - rabbitmq
    ports:
      - "8011:8011"
    env_file:
      - ./notifications/.env

  order-services:
    build: ./orders
    ports:
      - "8010:8010"
    env_file:
      - ./orders/.env

  user-services:
    build: ./users
    ports:
      - "8012:8012"
    env_file:
      - ./users/.env

  mongo-orders:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-orders:/data/db

  mongo-users:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo-users:/data/db

  mongo-notifications:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-notifications:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo-orders:
  mongo-notifications:
  mongo-users:
